apiVersion: apps/v1

kind: Deployment

metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
        - name: backend-feed
          image: sewunet/udagram-api-feed:1.0
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          envFrom:
            - configMapRef:
                name: udagram-config-map
            - secretRef:
                name: udagram-secret
          volumeMounts:
            - mountPath: "/root/.aws/"
              name: aws-config-map
      volumes:
        - name: aws-config-map
          configMap:
            name: aws-config-map
